### PR TITLE
Codewars

### PR DESCRIPTION
**Pull request by Silviia88**
Added codewars solutions

### CODE REVIEW

**Comment by rybassv** [comment]
2 solutions are missing, tasks.md missing too

**Comment by Silviia88** [comment]
Added tasks.md, have no idea how to do last 2 tasks

**Comment by rybassv** [comment]
> Added tasks.md, have no idea how to do last 2 tasks

You can always ask someone in Discord

**Comment by rybassv** [comment]
pls rename lerning_git branch into main or somethong so.

**Pull request merged**
